// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vXpA4gi5XGrKPdGTY7_KIW79OFvxezY',
    appId: '1:438002984280:web:1b0eeed65661379ef4b12d',
    messagingSenderId: '438002984280',
    projectId: 'aulas-e59eb',
    authDomain: 'aulas-e59eb.firebaseapp.com',
    storageBucket: 'aulas-e59eb.appspot.com',
    measurementId: 'G-TKD5ZK931Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4as2BqcHhUMYiryLUbEbS-S1eC29ojq0',
    appId: '1:438002984280:android:3862d1d6dbf9ef3ff4b12d',
    messagingSenderId: '438002984280',
    projectId: 'aulas-e59eb',
    storageBucket: 'aulas-e59eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJkOoYftpwgzCEjJXPUNVxkv0OBltva0',
    appId: '1:438002984280:ios:a749e2c0cdc94fa9f4b12d',
    messagingSenderId: '438002984280',
    projectId: 'aulas-e59eb',
    storageBucket: 'aulas-e59eb.appspot.com',
    iosBundleId: 'com.example.smartPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGJkOoYftpwgzCEjJXPUNVxkv0OBltva0',
    appId: '1:438002984280:ios:a749e2c0cdc94fa9f4b12d',
    messagingSenderId: '438002984280',
    projectId: 'aulas-e59eb',
    storageBucket: 'aulas-e59eb.appspot.com',
    iosBundleId: 'com.example.smartPark',
  );
}
